### ISSUE TITLE
Scope?

### ISSUE THREAD

**Issue by misslivirose** [mozilla/babw#2]
What is the scope of the project as we want to build it? Do we want to do something that is specific to the components Christian built, or something that can grow to encompass multiple avatar styles?

**Comment by johnshaughnessy** [comment]
I'd like to start as small as possible and then reassess. Specifically, the milestone I'd recommend we aim at is something like:

Build a standalone web application with these capabilities:
- It can be accessed on the public internet by a typical web browser (gh pages is ok)
- It provides a user interface for a person to combine the specific components that Christian built
- It shows a preview of the combined avatar
- It allows the combined avatar to be exported as a gltf or glb file.

From there, there will be plenty of extension / improvement opportunities, but this at least gives us a functional core to build and improve upon.
