### ISSUE TITLE
Do we build a standalone application or start with a fork of Hubs / Spoke?

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/babw#3]
John's opinion: I want to make it a standalone application because:
- It is not very time consuming to create one
- Having a consistent UI with Hubs/Spoke is not a requirement for this (hack week) project
- I want to get some practice standing up a simple web project
- It opens up more possibilities for things I'd like to experiment with in the future (creating a web backend, turning reticulum into an oauth provider and this application an oauth client)
- We could share this project as (another) example of a simple avatar builder that is compatible with hubs

**Comment by brianpeiris** [comment]
+1 to that. I don't think we'd easily be able to reuse 98% of the Hubs/Spoke codebase in this, so it's better to start from scratch
