### ISSUE TITLE
Javascript or Typescript?

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/babw#4]
John's opinion: I prefer to use javascript. I know a lot of people like typescript, so if anyone feels very strongly about it I'll cave. I don't know typescript yet, and do not feel particularly motivated to learn it as part of this project. I have some other places where I'd rather spend my learning tokens for this week, but I definitely want to be working in the web client.

**Comment by brianpeiris** [comment]
I have no strong preference here, but I agree we might spend more time learning TypeScript than we ought to for a hackweek.
