### ISSUE TITLE
Should we also build a backend application?

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/babw#5]
John's opinion: As a stretch goal -- _after_ we have a working browser-based program that allows you to combine avatar pieces and export them as an assembled avatar, I'd love try standing up an elixir application that could store your assembled avatars and one day act as an oauth client and plug directly into reticulum via the graphql api. Previously I've built a project with a few basic capabilities. I would have a lot of fun building something similar in order to "power up" this avatar creator. What I've built previously is:
- An elixir application that can upload and provide access to files in an s3 bucket
- A phoenix application that provides those capabilities via web apis (in reticulum these two are in one)
- A habitat script that bundles the phoenix application
- A packer script that creates an AMI to run the application
- Terraform scripts stand up an s3 bucket and an ec2 instance with the AMI

Some extension points we could build in might be:
- Accounts and letting people upload/share their own avatar pieces
- Direct integration with reticulum via Oauth
- Release the whole project as a "complete avatar creator in a box" that people could take and customize on their own. They could swap the front end client code so that their avatars have different structures/customizations, but handling assets / accounts / uploads / ops and everything else they'd need would be largely taken care of (assuming they want to use glb's and combine them the way we do, which I think is a fair assumption).

**Comment by brianpeiris** [comment]
IMO, I would generally avoid using elixir/phoenix when a node.js server would do just as well, mainly so that we don't alienate external contributors who might be interested in standalone projects like this.

**Comment by johnshaughnessy** [comment]
That's a good point. I've never written a node.js server but it is drastically simplifies the stack and the prerequisites people would need to meet in order to work with it.

I suppose I know how to talk to aws in javascript (via aws-cli). Do you know how to standup and talk to a database (if down the road, we want to explore that option)?

**Comment by johnshaughnessy** [comment]
It appears that creating a minimal server with express is not difficult. https://github.com/brianpeiris/quilt/blob/master/src/server/main.js

**Comment by brianpeiris** [comment]
Yup, and there are a number of ORM or DB helpers out there too. Popular options are Sequelize and Waterline. https://github.com/sequelize/sequelize https://github.com/balderdashy/waterline
